var constants = require("./const.js");

module.exports = [
    { "operation": constants.BRK, "mode": constants.SPECIAL, "immediate": null },
    { "operation": constants.ORA, "mode": constants.INDIRECT_X, "immediate": 8 },
    null,
    null,
    null,
    { "operation": constants.ORA, "mode": constants.ZEROPAGE, "immediate": 8 },
    { "operation": constants.ASL, "mode": constants.ZEROPAGE, "immediate": 8 },
    null,
    { "operation": constants.PHP, "mode": constants.SPECIAL, "immediate": null },
    { "operation": constants.ORA, "mode": constants.IMMEDIATE, "immediate": 8 },
    { "operation": constants.ASL, "mode": constants.ACCUMULATOR, "immediate": null },
    null,
    null,
    { "operation": constants.ORA, "mode": constants.ABSOLUTE, "immediate": 16 },
    { "operation": constants.ASL, "mode": constants.ABSOLUTE, "immediate": 16 },
    null,
    { "operation": constants.BPL, "mode": constants.RELATIVE, "immediate": -8 },
    { "operation": constants.ORA, "mode": constants.INDIRECT_Y, "immediate": 8 },
    null,
    null,
    null,
    { "operation": constants.ORA, "mode": constants.ZEROPAGE_X, "immediate": 8 },
    { "operation": constants.ASL, "mode": constants.ZEROPAGE_X, "immediate": 8 },
    null,
    { "operation": constants.CLC, "mode": constants.IMPLIED, "immediate": null },
    { "operation": constants.ORA, "mode": constants.ABSOLUTE_Y, "immediate": 16 },
    null,
    null,
    null,
    { "operation": constants.ORA, "mode": constants.ABSOLUTE_X, "immediate": 16 },
    { "operation": constants.ASL, "mode": constants.ABSOLUTE_X, "immediate": 16 },
    null,
    { "operation": constants.JSR, "mode": constants.SPECIAL, "immediate": 16 },
    { "operation": constants.AND, "mode": constants.INDIRECT_X, "immediate": 8 },
    null,
    null,
    { "operation": constants.BIT, "mode": constants.ZEROPAGE, "immediate": 8 },
    { "operation": constants.AND, "mode": constants.ZEROPAGE, "immediate": 8 },
    { "operation": constants.ROL, "mode": constants.ZEROPAGE, "immediate": 8 },
    null,
    { "operation": constants.PLP, "mode": constants.SPECIAL, "immediate": null },
    { "operation": constants.AND, "mode": constants.IMMEDIATE, "immediate": 8 },
    { "operation": constants.ROL, "mode": constants.ACCUMULATOR, "immediate": null },
    null,
    { "operation": constants.BIT, "mode": constants.ABSOLUTE, "immediate": 16 },
    { "operation": constants.AND, "mode": constants.ABSOLUTE, "immediate": 16 },
    { "operation": constants.ROL, "mode": constants.ABSOLUTE, "immediate": 16 },
    null,
    { "operation": constants.BMI, "mode": constants.RELATIVE, "immediate": -8 },
    { "operation": constants.AND, "mode": constants.INDIRECT_Y, "immediate": 8 },
    null,
    null,
    null,
    { "operation": constants.AND, "mode": constants.ZEROPAGE_X, "immediate": 8 },
    { "operation": constants.ROL, "mode": constants.ZEROPAGE_X, "immediate": 8 },
    null,
    { "operation": constants.SEC, "mode": constants.IMPLIED, "immediate": null },
    { "operation": constants.AND, "mode": constants.ABSOLUTE_Y, "immediate": 16 },
    null,
    null,
    null,
    { "operation": constants.AND, "mode": constants.ABSOLUTE_X, "immediate": 16 },
    { "operation": constants.ROL, "mode": constants.ABSOLUTE_X, "immediate": 16 },
    null,
    { "operation": constants.RTI, "mode": constants.SPECIAL, "immediate": null },
    { "operation": constants.EOR, "mode": constants.INDIRECT_X, "immediate": 8 },
    null,
    null,
    null,
    { "operation": constants.EOR, "mode": constants.ZEROPAGE, "immediate": 8 },
    { "operation": constants.LSR, "mode": constants.ZEROPAGE, "immediate": 8 },
    null,
    { "operation": constants.PHA, "mode": constants.SPECIAL, "immediate": null },
    { "operation": constants.EOR, "mode": constants.IMMEDIATE, "immediate": 8 },
    { "operation": constants.LSR, "mode": constants.ACCUMULATOR, "immediate": null },
    null,
    { "operation": constants.JMP, "mode": constants.ABSOLUTE, "immediate": 16 },
    { "operation": constants.EOR, "mode": constants.ABSOLUTE, "immediate": 16 },
    { "operation": constants.LSR, "mode": constants.ABSOLUTE, "immediate": 16 },
    null,
    { "operation": constants.BVC, "mode": constants.RELATIVE, "immediate": -8 },
    { "operation": constants.EOR, "mode": constants.INDIRECT_Y, "immediate": 8 },
    null,
    null,
    null,
    { "operation": constants.EOR, "mode": constants.ZEROPAGE_X, "immediate": 8 },
    { "operation": constants.LSR, "mode": constants.ZEROPAGE_X, "immediate": 8 },
    null,
    { "operation": constants.CLI, "mode": constants.IMPLIED, "immediate": null },
    { "operation": constants.EOR, "mode": constants.ABSOLUTE_Y, "immediate": 16 },
    null,
    null,
    null,
    { "operation": constants.EOR, "mode": constants.ABSOLUTE_X, "immediate": 16 },
    { "operation": constants.LSR, "mode": constants.ABSOLUTE_X, "immediate": 16 },
    null,
    { "operation": constants.RTS, "mode": constants.SPECIAL, "immediate": null },
    { "operation": constants.ADC, "mode": constants.INDIRECT_X, "immediate": 8 },
    null,
    null,
    null,
    { "operation": constants.ADC, "mode": constants.ZEROPAGE, "immediate": 8 },
    { "operation": constants.ROR, "mode": constants.ZEROPAGE, "immediate": 8 },
    null,
    { "operation": constants.PLA, "mode": constants.SPECIAL, "immediate": null },
    { "operation": constants.ADC, "mode": constants.IMMEDIATE, "immediate": 8 },
    { "operation": constants.ROR, "mode": constants.ACCUMULATOR, "immediate": null },
    null,
    { "operation": constants.JMP, "mode": constants.INDIRECT, "immediate": 16 },
    { "operation": constants.ADC, "mode": constants.ABSOLUTE, "immediate": 16 },
    { "operation": constants.ROR, "mode": constants.ABSOLUTE, "immediate": 16 },
    null,
    { "operation": constants.BVS, "mode": constants.RELATIVE, "immediate": -8 },
    { "operation": constants.ADC, "mode": constants.INDIRECT_Y, "immediate": 8 },
    null,
    null,
    null,
    { "operation": constants.ADC, "mode": constants.ZEROPAGE_X, "immediate": 8 },
    { "operation": constants.ROR, "mode": constants.ZEROPAGE_X, "immediate": 8 },
    null,
    { "operation": constants.SEI, "mode": constants.IMPLIED, "immediate": null },
    { "operation": constants.ADC, "mode": constants.ABSOLUTE_Y, "immediate": 16 },
    null,
    null,
    null,
    { "operation": constants.ADC, "mode": constants.ABSOLUTE_X, "immediate": 16 },
    { "operation": constants.ROR, "mode": constants.ABSOLUTE_X, "immediate": 16 },
    null,
    null,
    { "operation": constants.STA, "mode": constants.INDIRECT_X, "immediate": 8 },
    null,
    null,
    { "operation": constants.STY, "mode": constants.ZEROPAGE, "immediate": 8 },
    { "operation": constants.STA, "mode": constants.ZEROPAGE, "immediate": 8 },
    { "operation": constants.STX, "mode": constants.ZEROPAGE, "immediate": 8 },
    null,
    { "operation": constants.DEY, "mode": constants.IMPLIED, "immediate": null },
    null,
    { "operation": constants.TXA, "mode": constants.IMPLIED, "immediate": null },
    null,
    { "operation": constants.STY, "mode": constants.ABSOLUTE, "immediate": 16 },
    { "operation": constants.STA, "mode": constants.ABSOLUTE, "immediate": 16 },
    { "operation": constants.STX, "mode": constants.ABSOLUTE, "immediate": 16 },
    null,
    { "operation": constants.BCC, "mode": constants.RELATIVE, "immediate": -8 },
    { "operation": constants.STA, "mode": constants.INDIRECT_Y, "immediate": 8 },
    null,
    null,
    { "operation": constants.STY, "mode": constants.ZEROPAGE_X, "immediate": 8 },
    { "operation": constants.STA, "mode": constants.ZEROPAGE_X, "immediate": 8 },
    { "operation": constants.STX, "mode": constants.ZEROPAGE_Y, "immediate": 8 },
    null,
    { "operation": constants.TYA, "mode": constants.IMPLIED, "immediate": null },
    { "operation": constants.STA, "mode": constants.ABSOLUTE_Y, "immediate": 16 },
    { "operation": constants.TXS, "mode": constants.IMPLIED, "immediate": null },
    null,
    null,
    { "operation": constants.STA, "mode": constants.ABSOLUTE_X, "immediate": 16 },
    null,
    null,
    { "operation": constants.LDY, "mode": constants.IMMEDIATE, "immediate": 8 },
    { "operation": constants.LDA, "mode": constants.INDIRECT_X, "immediate": 8 },
    { "operation": constants.LDX, "mode": constants.IMMEDIATE, "immediate": 8 },
    null,
    { "operation": constants.LDY, "mode": constants.ZEROPAGE, "immediate": 8 },
    { "operation": constants.LDA, "mode": constants.ZEROPAGE, "immediate": 8 },
    { "operation": constants.LDX, "mode": constants.ZEROPAGE, "immediate": 8 },
    null,
    { "operation": constants.TAY, "mode": constants.IMPLIED, "immediate": null },
    { "operation": constants.LDA, "mode": constants.IMMEDIATE, "immediate": 8 },
    { "operation": constants.TAX, "mode": constants.IMPLIED, "immediate": null },
    null,
    { "operation": constants.LDY, "mode": constants.ABSOLUTE, "immediate": 16 },
    { "operation": constants.LDA, "mode": constants.ABSOLUTE, "immediate": 16 },
    { "operation": constants.LDX, "mode": constants.ABSOLUTE, "immediate": 16 },
    null,
    { "operation": constants.BCS, "mode": constants.RELATIVE, "immediate": -8 },
    { "operation": constants.LDA, "mode": constants.INDIRECT_Y, "immediate": 8 },
    null,
    null,
    { "operation": constants.LDY, "mode": constants.ZEROPAGE_X, "immediate": 8 },
    { "operation": constants.LDA, "mode": constants.ZEROPAGE_X, "immediate": 8 },
    { "operation": constants.LDX, "mode": constants.ZEROPAGE_Y, "immediate": 8 },
    null,
    { "operation": constants.CLV, "mode": constants.IMPLIED, "immediate": null },
    { "operation": constants.LDA, "mode": constants.ABSOLUTE_Y, "immediate": 16 },
    { "operation": constants.TSX, "mode": constants.IMPLIED, "immediate": null },
    null,
    { "operation": constants.LDY, "mode": constants.ABSOLUTE_X, "immediate": 16 },
    { "operation": constants.LDA, "mode": constants.ABSOLUTE_X, "immediate": 16 },
    { "operation": constants.LDX, "mode": constants.ABSOLUTE_Y, "immediate": 16 },
    null,
    { "operation": constants.CPY, "mode": constants.IMMEDIATE, "immediate": 8 },
    { "operation": constants.CMP, "mode": constants.INDIRECT_X, "immediate": 8 },
    null,
    null,
    { "operation": constants.CPY, "mode": constants.ZEROPAGE, "immediate": 8 },
    { "operation": constants.CMP, "mode": constants.ZEROPAGE, "immediate": 8 },
    { "operation": constants.DEC, "mode": constants.ZEROPAGE, "immediate": 8 },
    null,
    { "operation": constants.INY, "mode": constants.IMPLIED, "immediate": null },
    { "operation": constants.CMP, "mode": constants.IMMEDIATE, "immediate": 8 },
    { "operation": constants.DEX, "mode": constants.IMPLIED, "immediate": null },
    null,
    { "operation": constants.CPY, "mode": constants.ABSOLUTE, "immediate": 16 },
    { "operation": constants.CMP, "mode": constants.ABSOLUTE, "immediate": 16 },
    { "operation": constants.DEC, "mode": constants.ABSOLUTE, "immediate": 16 },
    null,
    { "operation": constants.BNE, "mode": constants.RELATIVE, "immediate": -8 },
    { "operation": constants.CMP, "mode": constants.INDIRECT_Y, "immediate": 8 },
    null,
    null,
    null,
    { "operation": constants.CMP, "mode": constants.ZEROPAGE_X, "immediate": 8 },
    { "operation": constants.DEC, "mode": constants.ZEROPAGE_X, "immediate": 8 },
    null,
    { "operation": constants.CLD, "mode": constants.IMPLIED, "immediate": null },
    { "operation": constants.CMP, "mode": constants.ABSOLUTE_Y, "immediate": 16 },
    null,
    null,
    null,
    { "operation": constants.CMP, "mode": constants.ABSOLUTE_X, "immediate": 16 },
    { "operation": constants.DEC, "mode": constants.ABSOLUTE_X, "immediate": 16 },
    null,
    { "operation": constants.CPX, "mode": constants.IMMEDIATE, "immediate": 8 },
    { "operation": constants.SBC, "mode": constants.INDIRECT_X, "immediate": 8 },
    null,
    null,
    { "operation": constants.CPX, "mode": constants.ZEROPAGE, "immediate": 8 },
    { "operation": constants.SBC, "mode": constants.ZEROPAGE, "immediate": 8 },
    { "operation": constants.INC, "mode": constants.ZEROPAGE, "immediate": 8 },
    null,
    { "operation": constants.INX, "mode": constants.IMPLIED, "immediate": null },
    { "operation": constants.SBC, "mode": constants.IMMEDIATE, "immediate": 8 },
    { "operation": constants.NOP, "mode": constants.IMPLIED, "immediate": null },
    null,
    { "operation": constants.CPX, "mode": constants.ABSOLUTE, "immediate": 16 },
    { "operation": constants.SBC, "mode": constants.ABSOLUTE, "immediate": 16 },
    { "operation": constants.INC, "mode": constants.ABSOLUTE, "immediate": 16 },
    null,
    { "operation": constants.BEQ, "mode": constants.RELATIVE, "immediate": -8 },
    { "operation": constants.SBC, "mode": constants.INDIRECT_Y, "immediate": 8 },
    null,
    null,
    null,
    { "operation": constants.SBC, "mode": constants.ZEROPAGE_X, "immediate": 8 },
    { "operation": constants.INC, "mode": constants.ZEROPAGE_X, "immediate": 8 },
    null,
    { "operation": constants.SED, "mode": constants.IMPLIED, "immediate": null },
    { "operation": constants.SBC, "mode": constants.ABSOLUTE_Y, "immediate": 16 },
    null,
    null,
    null,
    { "operation": constants.SBC, "mode": constants.ABSOLUTE_X, "immediate": 16 },
    { "operation": constants.INC, "mode": constants.ABSOLUTE_X, "immediate": 16 },
    null
];
