var constants = require("./const.js");

module.exports = [
    { "operation": "BRK", "mode": constants.SPECIAL, "immediate": null },
    { "operation": "ORA", "mode": constants.INDIRECT_X, "immediate": 8 },
    null,
    null,
    null,
    { "operation": "ORA", "mode": constants.ZEROPAGE, "immediate": 8 },
    { "operation": "ASL", "mode": constants.ZEROPAGE, "immediate": 8 },
    null,
    { "operation": "PHP", "mode": constants.SPECIAL, "immediate": null },
    { "operation": "ORA", "mode": constants.IMMEDIATE, "immediate": 8 },
    { "operation": "ASL", "mode": constants.ACCUMULATOR, "immediate": null },
    null,
    null,
    { "operation": "ORA", "mode": constants.ABSOLUTE, "immediate": 16 },
    { "operation": "ASL", "mode": constants.ABSOLUTE, "immediate": 16 },
    null,
    { "operation": "BPL", "mode": constants.RELATIVE, "immediate": -8 },
    { "operation": "ORA", "mode": constants.INDIRECT_Y, "immediate": 8 },
    null,
    null,
    null,
    { "operation": "ORA", "mode": constants.ZEROPAGE_X, "immediate": 8 },
    { "operation": "ASL", "mode": constants.ZEROPAGE_X, "immediate": 8 },
    null,
    { "operation": "CLC", "mode": constants.IMPLIED, "immediate": null },
    { "operation": "ORA", "mode": constants.ABSOLUTE_Y, "immediate": 16 },
    null,
    null,
    null,
    { "operation": "ORA", "mode": constants.ABSOLUTE_X, "immediate": 16 },
    { "operation": "ASL", "mode": constants.ABSOLUTE_X, "immediate": 16 },
    null,
    { "operation": "JSR", "mode": constants.SPECIAL, "immediate": 16 },
    { "operation": "AND", "mode": constants.INDIRECT_X, "immediate": 8 },
    null,
    null,
    { "operation": "BIT", "mode": constants.ZEROPAGE, "immediate": 8 },
    { "operation": "AND", "mode": constants.ZEROPAGE, "immediate": 8 },
    { "operation": "ROL", "mode": constants.ZEROPAGE, "immediate": 8 },
    null,
    { "operation": "PLP", "mode": constants.SPECIAL, "immediate": null },
    { "operation": "AND", "mode": constants.IMMEDIATE, "immediate": 8 },
    { "operation": "ROL", "mode": constants.ACCUMULATOR, "immediate": null },
    null,
    { "operation": "BIT", "mode": constants.ABSOLUTE, "immediate": 16 },
    { "operation": "AND", "mode": constants.ABSOLUTE, "immediate": 16 },
    { "operation": "ROL", "mode": constants.ABSOLUTE, "immediate": 16 },
    null,
    { "operation": "BMI", "mode": constants.RELATIVE, "immediate": -8 },
    { "operation": "AND", "mode": constants.INDIRECT_Y, "immediate": 8 },
    null,
    null,
    null,
    { "operation": "AND", "mode": constants.ZEROPAGE_X, "immediate": 8 },
    { "operation": "ROL", "mode": constants.ZEROPAGE_X, "immediate": 8 },
    null,
    { "operation": "SEC", "mode": constants.IMPLIED, "immediate": null },
    { "operation": "AND", "mode": constants.ABSOLUTE_Y, "immediate": 16 },
    null,
    null,
    null,
    { "operation": "AND", "mode": constants.ABSOLUTE_X, "immediate": 16 },
    { "operation": "ROL", "mode": constants.ABSOLUTE_X, "immediate": 16 },
    null,
    { "operation": "RTI", "mode": constants.SPECIAL, "immediate": null },
    { "operation": "EOR", "mode": constants.INDIRECT_X, "immediate": 8 },
    null,
    null,
    null,
    { "operation": "EOR", "mode": constants.ZEROPAGE, "immediate": 8 },
    { "operation": "LSR", "mode": constants.ZEROPAGE, "immediate": 8 },
    null,
    { "operation": "PHA", "mode": constants.SPECIAL, "immediate": null },
    { "operation": "EOR", "mode": constants.IMMEDIATE, "immediate": 8 },
    { "operation": "LSR", "mode": constants.ACCUMULATOR, "immediate": null },
    null,
    { "operation": "JMP", "mode": constants.ABSOLUTE, "immediate": 16 },
    { "operation": "EOR", "mode": constants.ABSOLUTE, "immediate": 16 },
    { "operation": "LSR", "mode": constants.ABSOLUTE, "immediate": 16 },
    null,
    { "operation": "BVC", "mode": constants.RELATIVE, "immediate": -8 },
    { "operation": "EOR", "mode": constants.INDIRECT_Y, "immediate": 8 },
    null,
    null,
    null,
    { "operation": "EOR", "mode": constants.ZEROPAGE_X, "immediate": 8 },
    { "operation": "LSR", "mode": constants.ZEROPAGE_X, "immediate": 8 },
    null,
    { "operation": "CLI", "mode": constants.IMPLIED, "immediate": null },
    { "operation": "EOR", "mode": constants.ABSOLUTE_Y, "immediate": 16 },
    null,
    null,
    null,
    { "operation": "EOR", "mode": constants.ABSOLUTE_X, "immediate": 16 },
    { "operation": "LSR", "mode": constants.ABSOLUTE_X, "immediate": 16 },
    null,
    { "operation": "RTS", "mode": constants.SPECIAL, "immediate": null },
    { "operation": "ADC", "mode": constants.INDIRECT_X, "immediate": 8 },
    null,
    null,
    null,
    { "operation": "ADC", "mode": constants.ZEROPAGE, "immediate": 8 },
    { "operation": "ROR", "mode": constants.ZEROPAGE, "immediate": 8 },
    null,
    { "operation": "PLA", "mode": constants.SPECIAL, "immediate": null },
    { "operation": "ADC", "mode": constants.IMMEDIATE, "immediate": 8 },
    { "operation": "ROR", "mode": constants.ACCUMULATOR, "immediate": null },
    null,
    { "operation": "JMP", "mode": constants.INDIRECT, "immediate": 16 },
    { "operation": "ADC", "mode": constants.ABSOLUTE, "immediate": 16 },
    { "operation": "ROR", "mode": constants.ABSOLUTE, "immediate": 16 },
    null,
    { "operation": "BVS", "mode": constants.RELATIVE, "immediate": -8 },
    { "operation": "ADC", "mode": constants.INDIRECT_Y, "immediate": 8 },
    null,
    null,
    null,
    { "operation": "ADC", "mode": constants.ZEROPAGE_X, "immediate": 8 },
    { "operation": "ROR", "mode": constants.ZEROPAGE_X, "immediate": 8 },
    null,
    { "operation": "SEI", "mode": constants.IMPLIED, "immediate": null },
    { "operation": "ADC", "mode": constants.ABSOLUTE_Y, "immediate": 16 },
    null,
    null,
    null,
    { "operation": "ADC", "mode": constants.ABSOLUTE_X, "immediate": 16 },
    { "operation": "ROR", "mode": constants.ABSOLUTE_X, "immediate": 16 },
    null,
    null,
    { "operation": "STA", "mode": constants.INDIRECT_X, "immediate": 8 },
    null,
    null,
    { "operation": "STY", "mode": constants.ZEROPAGE, "immediate": 8 },
    { "operation": "STA", "mode": constants.ZEROPAGE, "immediate": 8 },
    { "operation": "STX", "mode": constants.ZEROPAGE, "immediate": 8 },
    null,
    { "operation": "DEY", "mode": constants.IMPLIED, "immediate": null },
    null,
    { "operation": "TXA", "mode": constants.IMPLIED, "immediate": null },
    null,
    { "operation": "STY", "mode": constants.ABSOLUTE, "immediate": 16 },
    { "operation": "STA", "mode": constants.ABSOLUTE, "immediate": 16 },
    { "operation": "STX", "mode": constants.ABSOLUTE, "immediate": 16 },
    null,
    { "operation": "BCC", "mode": constants.RELATIVE, "immediate": -8 },
    { "operation": "STA", "mode": constants.INDIRECT_Y, "immediate": 8 },
    null,
    null,
    { "operation": "STY", "mode": constants.ZEROPAGE_X, "immediate": 8 },
    { "operation": "STA", "mode": constants.ZEROPAGE_X, "immediate": 8 },
    { "operation": "STX", "mode": constants.ZEROPAGE_Y, "immediate": 8 },
    null,
    { "operation": "TYA", "mode": constants.IMPLIED, "immediate": null },
    { "operation": "STA", "mode": constants.ABSOLUTE_Y, "immediate": 16 },
    { "operation": "TXS", "mode": constants.IMPLIED, "immediate": null },
    null,
    null,
    { "operation": "STA", "mode": constants.ABSOLUTE_X, "immediate": 16 },
    null,
    null,
    { "operation": "LDY", "mode": constants.IMMEDIATE, "immediate": 8 },
    { "operation": "LDA", "mode": constants.INDIRECT_X, "immediate": 8 },
    { "operation": "LDX", "mode": constants.IMMEDIATE, "immediate": 8 },
    null,
    { "operation": "LDY", "mode": constants.ZEROPAGE, "immediate": 8 },
    { "operation": "LDA", "mode": constants.ZEROPAGE, "immediate": 8 },
    { "operation": "LDX", "mode": constants.ZEROPAGE, "immediate": 8 },
    null,
    { "operation": "TAY", "mode": constants.IMPLIED, "immediate": null },
    { "operation": "LDA", "mode": constants.IMMEDIATE, "immediate": 8 },
    { "operation": "TAX", "mode": constants.IMPLIED, "immediate": null },
    null,
    { "operation": "LDY", "mode": constants.ABSOLUTE, "immediate": 16 },
    { "operation": "LDA", "mode": constants.ABSOLUTE, "immediate": 16 },
    { "operation": "LDX", "mode": constants.ABSOLUTE, "immediate": 16 },
    null,
    { "operation": "BCS", "mode": constants.RELATIVE, "immediate": -8 },
    { "operation": "LDA", "mode": constants.INDIRECT_Y, "immediate": 8 },
    null,
    null,
    { "operation": "LDY", "mode": constants.ZEROPAGE_X, "immediate": 8 },
    { "operation": "LDA", "mode": constants.ZEROPAGE_X, "immediate": 8 },
    { "operation": "LDX", "mode": constants.ZEROPAGE_Y, "immediate": 8 },
    null,
    { "operation": "CLV", "mode": constants.IMPLIED, "immediate": null },
    { "operation": "LDA", "mode": constants.ABSOLUTE_Y, "immediate": 16 },
    { "operation": "TSX", "mode": constants.IMPLIED, "immediate": null },
    null,
    { "operation": "LDY", "mode": constants.ABSOLUTE_X, "immediate": 16 },
    { "operation": "LDA", "mode": constants.ABSOLUTE_X, "immediate": 16 },
    { "operation": "LDX", "mode": constants.ABSOLUTE_Y, "immediate": 16 },
    null,
    { "operation": "CPY", "mode": constants.IMMEDIATE, "immediate": 8 },
    { "operation": "CMP", "mode": constants.INDIRECT_X, "immediate": 8 },
    null,
    null,
    { "operation": "CPY", "mode": constants.ZEROPAGE, "immediate": 8 },
    { "operation": "CMP", "mode": constants.ZEROPAGE, "immediate": 8 },
    { "operation": "DEC", "mode": constants.ZEROPAGE, "immediate": 8 },
    null,
    { "operation": "INY", "mode": constants.IMPLIED, "immediate": null },
    { "operation": "CMP", "mode": constants.IMMEDIATE, "immediate": 8 },
    { "operation": "DEX", "mode": constants.IMPLIED, "immediate": null },
    null,
    { "operation": "CPY", "mode": constants.ABSOLUTE, "immediate": 16 },
    { "operation": "CMP", "mode": constants.ABSOLUTE, "immediate": 16 },
    { "operation": "DEC", "mode": constants.ABSOLUTE, "immediate": 16 },
    null,
    { "operation": "BNE", "mode": constants.RELATIVE, "immediate": -8 },
    { "operation": "CMP", "mode": constants.INDIRECT_Y, "immediate": 8 },
    null,
    null,
    null,
    { "operation": "CMP", "mode": constants.ZEROPAGE_X, "immediate": 8 },
    { "operation": "DEC", "mode": constants.ZEROPAGE_X, "immediate": 8 },
    null,
    { "operation": "CLD", "mode": constants.IMPLIED, "immediate": null },
    { "operation": "CMP", "mode": constants.ABSOLUTE_Y, "immediate": 16 },
    null,
    null,
    null,
    { "operation": "CMP", "mode": constants.ABSOLUTE_X, "immediate": 16 },
    { "operation": "DEC", "mode": constants.ABSOLUTE_X, "immediate": 16 },
    null,
    { "operation": "CPX", "mode": constants.IMMEDIATE, "immediate": 8 },
    { "operation": "SBC", "mode": constants.INDIRECT_X, "immediate": 8 },
    null,
    null,
    { "operation": "CPX", "mode": constants.ZEROPAGE, "immediate": 8 },
    { "operation": "SBC", "mode": constants.ZEROPAGE, "immediate": 8 },
    { "operation": "INC", "mode": constants.ZEROPAGE, "immediate": 8 },
    null,
    { "operation": "INX", "mode": constants.IMPLIED, "immediate": null },
    { "operation": "SBC", "mode": constants.IMMEDIATE, "immediate": 8 },
    { "operation": "NOP", "mode": constants.IMPLIED, "immediate": null },
    null,
    { "operation": "CPX", "mode": constants.ABSOLUTE, "immediate": 16 },
    { "operation": "SBC", "mode": constants.ABSOLUTE, "immediate": 16 },
    { "operation": "INC", "mode": constants.ABSOLUTE, "immediate": 16 },
    null,
    { "operation": "BEQ", "mode": constants.RELATIVE, "immediate": -8 },
    { "operation": "SBC", "mode": constants.INDIRECT_Y, "immediate": 8 },
    null,
    null,
    null,
    { "operation": "SBC", "mode": constants.ZEROPAGE_X, "immediate": 8 },
    { "operation": "INC", "mode": constants.ZEROPAGE_X, "immediate": 8 },
    null,
    { "operation": "SED", "mode": constants.IMPLIED, "immediate": null },
    { "operation": "SBC", "mode": constants.ABSOLUTE_Y, "immediate": 16 },
    null,
    null,
    null,
    { "operation": "SBC", "mode": constants.ABSOLUTE_X, "immediate": 16 },
    { "operation": "INC", "mode": constants.ABSOLUTE_X, "immediate": 16 },
    null
];
